name: PR E2E

on:
  pull_request:
    branches: ["**"]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm -w install

      - name: Lint
        run: pnpm -w lint

      - name: Typecheck
        run: pnpm -w typecheck

      - name: Build
        run: pnpm -w build

      - name: Install Playwright browsers
        run: pnpm -w dlx playwright install --with-deps

      - name: Run full E2E with retries and collect artifacts
        run: |
          pnpm -w test:e2e -- --retries=1 || true
          mkdir -p artifacts
          cp -r apps/app/playwright-report artifacts/ || true
          cp -r apps/app/test-results artifacts/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: artifacts
